ALTER TABLE public.sales ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE public.sales_lines ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE public.inventory ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE public.finance_ar_open_items ADD COLUMN id SERIAL PRIMARY KEY;
