ALTER TABLE public.sales DROP COLUMN IF EXISTS id CASCADE;
ALTER TABLE public.sales_lines DROP COLUMN IF EXISTS id CASCADE;
ALTER TABLE public.inventory DROP COLUMN IF EXISTS id CASCADE;
ALTER TABLE public.finance_ar_open_items DROP COLUMN IF EXISTS id CASCADE;
