-- Migration n018: Rollback

DROP POLICY IF EXISTS n018_raw_netsuite_customers_select_own_tenant ON raw_netsuite_customers;
DROP POLICY IF EXISTS n018_raw_netsuite_customers_insert_own_tenant ON raw_netsuite_customers;
DROP POLICY IF EXISTS n018_raw_netsuite_customers_update_own_tenant ON raw_netsuite_customers;
DROP POLICY IF EXISTS n018_raw_netsuite_customers_delete_own_tenant ON raw_netsuite_customers;

DROP POLICY IF EXISTS n018_raw_collections_select_own_tenant ON raw_collections;
DROP POLICY IF EXISTS n018_raw_collections_insert_own_tenant ON raw_collections;
DROP POLICY IF EXISTS n018_raw_collections_update_own_tenant ON raw_collections;
DROP POLICY IF EXISTS n018_raw_collections_delete_own_tenant ON raw_collections;

DROP POLICY IF EXISTS n018_raw_customers_select_own_tenant ON raw_customers;
DROP POLICY IF EXISTS n018_raw_customers_insert_own_tenant ON raw_customers;
DROP POLICY IF EXISTS n018_raw_customers_update_own_tenant ON raw_customers;
DROP POLICY IF EXISTS n018_raw_customers_delete_own_tenant ON raw_customers;

DROP POLICY IF EXISTS n018_raw_sales_lines_select_own_tenant ON raw_sales_lines;
DROP POLICY IF EXISTS n018_raw_sales_lines_insert_own_tenant ON raw_sales_lines;
DROP POLICY IF EXISTS n018_raw_sales_lines_update_own_tenant ON raw_sales_lines;
DROP POLICY IF EXISTS n018_raw_sales_lines_delete_own_tenant ON raw_sales_lines;

DROP POLICY IF EXISTS n018_stg_inventory_transactions_clean_select_own_tenant ON stg_inventory_transactions_clean;
DROP POLICY IF EXISTS n018_stg_inventory_transactions_clean_insert_own_tenant ON stg_inventory_transactions_clean;
DROP POLICY IF EXISTS n018_stg_inventory_transactions_clean_update_own_tenant ON stg_inventory_transactions_clean;
DROP POLICY IF EXISTS n018_stg_inventory_transactions_clean_delete_own_tenant ON stg_inventory_transactions_clean;

DROP POLICY IF EXISTS n018_raw_sales_select_own_tenant ON raw_sales;
DROP POLICY IF EXISTS n018_raw_sales_insert_own_tenant ON raw_sales;
DROP POLICY IF EXISTS n018_raw_sales_update_own_tenant ON raw_sales;
DROP POLICY IF EXISTS n018_raw_sales_delete_own_tenant ON raw_sales;

DROP POLICY IF EXISTS n018_stg_customers_clean_select_own_tenant ON stg_customers_clean;
DROP POLICY IF EXISTS n018_stg_customers_clean_insert_own_tenant ON stg_customers_clean;
DROP POLICY IF EXISTS n018_stg_customers_clean_update_own_tenant ON stg_customers_clean;
DROP POLICY IF EXISTS n018_stg_customers_clean_delete_own_tenant ON stg_customers_clean;

DROP POLICY IF EXISTS n018_raw_subsidiaries_select_own_tenant ON raw_subsidiaries;
DROP POLICY IF EXISTS n018_raw_subsidiaries_insert_own_tenant ON raw_subsidiaries;
DROP POLICY IF EXISTS n018_raw_subsidiaries_update_own_tenant ON raw_subsidiaries;
DROP POLICY IF EXISTS n018_raw_subsidiaries_delete_own_tenant ON raw_subsidiaries;

DROP POLICY IF EXISTS n018_raw_locations_select_own_tenant ON raw_locations;
DROP POLICY IF EXISTS n018_raw_locations_insert_own_tenant ON raw_locations;
DROP POLICY IF EXISTS n018_raw_locations_update_own_tenant ON raw_locations;
DROP POLICY IF EXISTS n018_raw_locations_delete_own_tenant ON raw_locations;

DROP POLICY IF EXISTS n018_stg_sales_lines_clean_select_own_tenant ON stg_sales_lines_clean;
DROP POLICY IF EXISTS n018_stg_sales_lines_clean_insert_own_tenant ON stg_sales_lines_clean;
DROP POLICY IF EXISTS n018_stg_sales_lines_clean_update_own_tenant ON stg_sales_lines_clean;
DROP POLICY IF EXISTS n018_stg_sales_lines_clean_delete_own_tenant ON stg_sales_lines_clean;

DROP POLICY IF EXISTS n018_raw_ar_open_items_select_own_tenant ON raw_ar_open_items;
DROP POLICY IF EXISTS n018_raw_ar_open_items_insert_own_tenant ON raw_ar_open_items;
DROP POLICY IF EXISTS n018_raw_ar_open_items_update_own_tenant ON raw_ar_open_items;
DROP POLICY IF EXISTS n018_raw_ar_open_items_delete_own_tenant ON raw_ar_open_items;

DROP POLICY IF EXISTS n018_stg_sales_clean_select_own_tenant ON stg_sales_clean;
DROP POLICY IF EXISTS n018_stg_sales_clean_insert_own_tenant ON stg_sales_clean;
DROP POLICY IF EXISTS n018_stg_sales_clean_update_own_tenant ON stg_sales_clean;
DROP POLICY IF EXISTS n018_stg_sales_clean_delete_own_tenant ON stg_sales_clean;

DROP POLICY IF EXISTS n018_raw_customer_payments_select_own_tenant ON raw_customer_payments;
DROP POLICY IF EXISTS n018_raw_customer_payments_insert_own_tenant ON raw_customer_payments;
DROP POLICY IF EXISTS n018_raw_customer_payments_update_own_tenant ON raw_customer_payments;
DROP POLICY IF EXISTS n018_raw_customer_payments_delete_own_tenant ON raw_customer_payments;

DROP POLICY IF EXISTS n018_raw_inbound_shipments_select_own_tenant ON raw_inbound_shipments;
DROP POLICY IF EXISTS n018_raw_inbound_shipments_insert_own_tenant ON raw_inbound_shipments;
DROP POLICY IF EXISTS n018_raw_inbound_shipments_update_own_tenant ON raw_inbound_shipments;
DROP POLICY IF EXISTS n018_raw_inbound_shipments_delete_own_tenant ON raw_inbound_shipments;

DROP POLICY IF EXISTS n018_raw_inventory_select_own_tenant ON raw_inventory;
DROP POLICY IF EXISTS n018_raw_inventory_insert_own_tenant ON raw_inventory;
DROP POLICY IF EXISTS n018_raw_inventory_update_own_tenant ON raw_inventory;
DROP POLICY IF EXISTS n018_raw_inventory_delete_own_tenant ON raw_inventory;

DROP POLICY IF EXISTS n018_raw_inventory_transactions_select_own_tenant ON raw_inventory_transactions;
DROP POLICY IF EXISTS n018_raw_inventory_transactions_insert_own_tenant ON raw_inventory_transactions;
DROP POLICY IF EXISTS n018_raw_inventory_transactions_update_own_tenant ON raw_inventory_transactions;
DROP POLICY IF EXISTS n018_raw_inventory_transactions_delete_own_tenant ON raw_inventory_transactions;

DROP POLICY IF EXISTS n018_stg_inbound_shipments_clean_select_own_tenant ON stg_inbound_shipments_clean;
DROP POLICY IF EXISTS n018_stg_inbound_shipments_clean_insert_own_tenant ON stg_inbound_shipments_clean;
DROP POLICY IF EXISTS n018_stg_inbound_shipments_clean_update_own_tenant ON stg_inbound_shipments_clean;
DROP POLICY IF EXISTS n018_stg_inbound_shipments_clean_delete_own_tenant ON stg_inbound_shipments_clean;

DROP POLICY IF EXISTS n018_stg_items_master_clean_select_own_tenant ON stg_items_master_clean;
DROP POLICY IF EXISTS n018_stg_items_master_clean_insert_own_tenant ON stg_items_master_clean;
DROP POLICY IF EXISTS n018_stg_items_master_clean_update_own_tenant ON stg_items_master_clean;
DROP POLICY IF EXISTS n018_stg_items_master_clean_delete_own_tenant ON stg_items_master_clean;

DROP POLICY IF EXISTS n018_raw_items_master_select_own_tenant ON raw_items_master;
DROP POLICY IF EXISTS n018_raw_items_master_insert_own_tenant ON raw_items_master;
DROP POLICY IF EXISTS n018_raw_items_master_update_own_tenant ON raw_items_master;
DROP POLICY IF EXISTS n018_raw_items_master_delete_own_tenant ON raw_items_master;

DROP POLICY IF EXISTS n018_stg_customer_payments_clean_select_own_tenant ON stg_customer_payments_clean;
DROP POLICY IF EXISTS n018_stg_customer_payments_clean_insert_own_tenant ON stg_customer_payments_clean;
DROP POLICY IF EXISTS n018_stg_customer_payments_clean_update_own_tenant ON stg_customer_payments_clean;
DROP POLICY IF EXISTS n018_stg_customer_payments_clean_delete_own_tenant ON stg_customer_payments_clean;

DROP POLICY IF EXISTS n018_raw_item_bom_select_own_tenant ON raw_item_bom;
DROP POLICY IF EXISTS n018_raw_item_bom_insert_own_tenant ON raw_item_bom;
DROP POLICY IF EXISTS n018_raw_item_bom_update_own_tenant ON raw_item_bom;
DROP POLICY IF EXISTS n018_raw_item_bom_delete_own_tenant ON raw_item_bom;

DROP POLICY IF EXISTS n018_raw_open_sales_orders_select_own_tenant ON raw_open_sales_orders;
DROP POLICY IF EXISTS n018_raw_open_sales_orders_insert_own_tenant ON raw_open_sales_orders;
DROP POLICY IF EXISTS n018_raw_open_sales_orders_update_own_tenant ON raw_open_sales_orders;
DROP POLICY IF EXISTS n018_raw_open_sales_orders_delete_own_tenant ON raw_open_sales_orders;

DROP POLICY IF EXISTS n018_stg_ar_open_items_clean_select_own_tenant ON stg_ar_open_items_clean;
DROP POLICY IF EXISTS n018_stg_ar_open_items_clean_insert_own_tenant ON stg_ar_open_items_clean;
DROP POLICY IF EXISTS n018_stg_ar_open_items_clean_update_own_tenant ON stg_ar_open_items_clean;
DROP POLICY IF EXISTS n018_stg_ar_open_items_clean_delete_own_tenant ON stg_ar_open_items_clean;

